name: resynth
description: "ReSynth VPN"
publish_to: 'none'

version: 5.5.0+7

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  intl: ^0.19.0  # ğŸ†• Ø§Ø¶Ø§ÙÙ‡ Ø´Ø¯ - Ø¨Ø±Ø§ÛŒ Ø§Ø¹Ø¯Ø§Ø¯ Ø§Ù†Ú¯Ù„ÛŒØ³ÛŒ
  flutter_v2ray:
    git:
      url: https://github.com/motad-dev/flutter_v2ray
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  awesome_dialog: ^3.2.1
  device_info_plus: ^10.1.2
  encrypt: ^5.0.3
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  installed_apps: ^1.5.2
  flutter_settings_ui: ^3.0.1
  easy_localization: ^3.0.7
  iconsax: ^0.0.8
  loading_animation_widget: ^1.3.0
  lottie: ^3.1.3
  safe_device: ^1.1.9
  vpn_connection_detector: ^1.0.9
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  cryptography: ^2.7.0
  pointycastle: ^3.7.3
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/lottie/

  fonts:
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400
    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500
    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700
    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800
    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900
    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500
    - family: SB
      fonts:
        - asset: assets/fonts/ShabnamBold.ttf
          weight: 700
    - family: dana
      fonts:
        - asset: assets/fonts/dana.ttf
          weight: 500
