dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  
  # VPN Client - New
  flutter_v2ray_client:
    git:
      url: https://github.com/amir-zr/flutter_v2ray_client
      ref: main
  
  # State Management  
  flutter_riverpod: ^2.4.9
  
  # HTTP
  http: ^1.1.0
  
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1
  awesome_dialog: ^3.2.1
  device_info_plus: ^10.1.2
  encrypt: ^5.0.3
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  installed_apps: ^1.5.2
  flutter_settings_ui: ^3.0.1
  easy_localization: ^3.0.7
  iconsax: ^0.0.8
  loading_animation_widget: ^1.3.0
  lottie: ^3.1.3
  safe_device: ^1.1.9
  vpn_connection_detector: ^1.0.9
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  cryptography: ^2.7.0
  pointycastle: ^3.7.3
  flutter_secure_storage: ^9.2.2
