name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: دانلود کد
      uses: actions/checkout@v4
      
    - name: نصب Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: نصب Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        
    - name: نصب پکیج‌ها
      run: flutter pub get
      
    - name: بیلد APK
      run: flutter build apk --release
      
    - name: آپلود APK
      uses: actions/upload-artifact@v4
      with:
        name: ReSynthApp-release
        path: build/app/outputs/flutter-apk/app-release.apk
